### ISSUE TITLE
Optimisation

### ISSUE THREAD

**Issue by ocimjr** [3hhh/xtalk#1]
Since your code was moved, I cannot comment on old threat.

By chance, I was searching for a hairmidi replacement for mac, I found this https://github.com/RuudMulder/SerialMidiBridge/blob/main/SerialMidiBridge.py

He used thread and midi on his code. This can maybe help to not use "while" to wait for midi messages.

Hope it helps,

**Comment by 3hhh** [comment]
Thanks for the link!

The author however is using neither rtmidi nor asyncio and I definitely want to keep those two.

**Comment by ocimjr** [comment]
He is using rtmidi see lines 23 and 24.
Is true he is not using Asyncio, but he is use threading, 

> `s_watcher = threading.Thread(target = serial_watcher)`

Maybe this could be use in the same way with asyncio
